version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db  # Use the service name of the MySQL container
      MYSQL_USER: root
      MYSQL_PASSWORD:  # Leave empty if no password is set
      MYSQL_DB: project
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  # Add the root password for your MySQL database, or leave empty if no password is set
      MYSQL_DATABASE: project
